/**
 * Love Land 闯关内容表
 * 之后补文案、NPC、玩法：主要改这个文件即可。
 * 标记 【待补充】 的字段可以逐条替换。
 */
window.GAME_DATA = {
  meta: {
    title: "Escape to Love Land",
    subtitle: "一场以爱为名的逃跑计划",
    couple: "小钟 & 阿旭",
    venue: "成都 · 右岸天鹅湖民宿",
    dates: "2026.09.25 — 09.26",
    inviteUrl: "https://escapetoloveland.com/invite",
  },

  letter: {
    greeting: "我最亲爱的家人和朋友",
    body: [
      "生命本就是小概率事件",
      "在时间的荒野和空间的无限中排列",
      "在几亿亿个可能性里",
      "我们最终相遇",
      "",
      "收到邀请函的你们",
      "皆是我们生命在不同经纬",
      "所遇见的最重要的人",
      "",
      "诚邀你们参加这场以爱为名的逃跑计划",
      "共同分享这美妙的一天",
      "聚散有期，情谊无疆",
      "祝有爱者更爱 独立者更自由",
    ],
    sign: "小钟 & 阿旭",
    hint: "拆开纸船，获取信件",
  },

  items: {
    letter: { name: "纸船邀请函", icon: "⛵" },
    bingo: { name: "Bingo Card", icon: "🃏" },
    glow: { name: "荧光棒", icon: "🌟" },
    spray: { name: "驱蚊液", icon: "🧴" },
    pass: { name: "签到门票", icon: "🎟️" },
    ticket: { name: "Love Land 入场券", icon: "🎫" },
    gift: { name: "专属伴手礼", icon: "🎁" },
    photo: { name: "现场合影", icon: "📷" },
    boothSnap: { name: "游园会合影", icon: "🖼️" },
    welcome: { name: "欢迎卡", icon: "💌" },
    partyflow: { name: "Party 流程单", icon: "📋" },
    vowcard: { name: "问誓卡", icon: "🤍" },
    dessert: { name: "甜品小食", icon: "🍰" },
    seatmap: { name: "座位图", icon: "🗺️" },
    bracelet: { name: "手串", icon: "📿" },
    sachet: { name: "香囊", icon: "🎀" },
    balloon: { name: "游乐场气球", icon: "🎈" },
  },

  currencyHelp: {
    title: "筹码和游戏币有什么不同？",
    body: [
      "9.25 晚上主要用【筹码】。现场筹码有 10、50、100、200、500、1000 六种面额（见下图），Party 拍卖按面额计价。",
      "筹码来源：参加破冰、赌坊猜大小、在草地凳子下找散落筹码等。",
      "当天没用完的筹码，第二天会忽略面额，按张数变成【游戏币】——一枚无论是 50 还是 1000，都只算 1 枚游戏币。",
      "游戏币在 9.26 游园会上兑换礼物。",
    ],
    image: "assets/chips.jpeg",
  },

  bingoCells: [
    { id: "kailash", prompt: "在冈仁波齐转过山" },
    { id: "marathon", prompt: "马拉松完赛过" },
    { id: "dive", prompt: "在巴厘岛考得了潜水证" },
    { id: "piano", prompt: "会弹钢琴" },
    { id: "years15", prompt: "和新郎/新娘认识15年以上" },
    { id: "lab", prompt: "读研期间和新郎/新娘在同一实验室" },
    { id: "dorm", prompt: "和新郎/新娘住过同一寝室" },
    { id: "phd", prompt: "取得博士学位" },
    { id: "wedyear", prompt: "婚期也在今年的朋友" },
    { id: "cards", prompt: "掼蛋/麻将赢过新郎新娘" },
    { id: "travel", prompt: "和新郎/新娘一起旅游过" },
    { id: "festival", prompt: "和新郎/新娘一起参加过音乐节" },
    { id: "teacher", prompt: "职业为老师" },
    { id: "cat", prompt: "小猫咪铲屎官" },
    { id: "chouchou", prompt: "“臭臭”的爸爸/妈妈" },
    { id: "cook", prompt: "给新郎/新娘做过饭吃的" },
  ],

  guests: [
    {
      id: "zhou",
      name: "周山",
      shirt: 0x5c7a4a,
      hair: 0x2a2018,
      hello: "刚转完冈仁波齐，腿还在抖，就飞来喝喜酒了。",
      tags: ["kailash"],
      questions: [
        { ask: "你去过冈仁波齐吗？", bingo: "kailash", yes: "转过。那座山会把人变安静一点。" },
        { ask: "今天怎么过来的？", bingo: null, yes: "和大家一样，逃向 Love Land。" },
      ],
    },
    {
      id: "hua",
      name: "阿花",
      shirt: 0xd47aa0,
      hair: 0x4a2018,
      hello: "我去年刚跑完马拉松，现在改成跑婚礼了。",
      tags: ["marathon"],
      questions: [
        { ask: "你跑过马拉松吗？", bingo: "marathon", yes: "完赛过！奖牌还压在行李箱里。" },
        { ask: "待会破冰一起组队？", bingo: null, yes: "好啊，我负责跑腿。" },
      ],
    },
    {
      id: "lin",
      name: "林潜",
      shirt: 0x3d7ea6,
      hair: 0x1a1a1a,
      hello: "巴厘岛刚考完潜水证，耳朵还嗡嗡的。",
      tags: ["dive"],
      questions: [
        { ask: "请问你喜欢潜水吗？", bingo: "dive", yes: "喜欢。我在巴厘岛考了证，水下世界太安静了。" },
        { ask: "成都有海吗？", bingo: null, yes: "没有海，但有天鹅湖，也算一种水。" },
      ],
    },
    {
      id: "chen",
      name: "陈琴",
      shirt: 0x7b4ea3,
      hair: 0x3b2a1d,
      hello: "今晚要是有钢琴我就献丑。也给新娘做过一顿面。",
      tags: ["piano", "cook"],
      questions: [
        { ask: "你会弹钢琴吗？", bingo: "piano", yes: "会。别点很难的，今晚只弹好听的。" },
        { ask: "你给新郎新娘做过饭吗？", bingo: "cook", yes: "做过。新娘说那碗面能续命。" },
      ],
    },
    {
      id: "wu",
      name: "老吴",
      shirt: 0x6b5344,
      hair: 0x4a4038,
      hello: "认识他们超过十五年了，看着长大的那种。",
      tags: ["years15"],
      questions: [
        { ask: "你和新郎新娘认识很久了吧？", bingo: "years15", yes: "十五年以上。大学之前就认识了。" },
        { ask: "有什么要嘱咐新人的？", bingo: null, yes: "好好吃饭，好好睡觉，好好相爱。" },
      ],
    },
    {
      id: "le",
      name: "阿乐",
      shirt: 0xc45c4a,
      hair: 0x221510,
      hello: "我们一起挤过音乐节，装备还在我车上。",
      tags: ["festival"],
      questions: [
        { ask: "你和他们一起去过音乐节吗？", bingo: "festival", yes: "去过。晒脱皮那种。" },
        { ask: "待会合唱《干杯》你会吗？", bingo: null, yes: "副歌会。重要的是一起大声唱。" },
      ],
    },
    {
      id: "qi",
      name: "阿琪",
      shirt: 0x4a6b8a,
      hair: 0x2c1810,
      hello: "读研那会儿实验室就三个人，两个现在结婚了。",
      tags: ["lab"],
      questions: [
        { ask: "你们读研在同一个实验室吗？", bingo: "lab", yes: "对，同一间实验室，抢过同一台离心机。" },
        { ask: "实验好做吗？", bingo: null, yes: "不好做。所以更要来喝喜酒。" },
      ],
    },
    {
      id: "bei",
      name: "小北",
      shirt: 0xe8d9a8,
      hair: 0x3a2a20,
      hello: "大学室友。我家猫叫布丁，我是专职铲屎官。",
      tags: ["dorm", "cat"],
      questions: [
        { ask: "你和新郎新娘住过同一间寝室？", bingo: "dorm", yes: "住过。打呼声我可以出公证。" },
        { ask: "你养猫吗？", bingo: "cat", yes: "养。我就是小猫咪铲屎官本人。" },
      ],
    },
    {
      id: "wumiao",
      name: "吴淼",
      shirt: 0x2f3d55,
      hair: 0x1c1410,
      hello: "博士读完才敢来喝这杯。论文比婚礼难。旁边那位是小糖博士，别看她甜，答辩比我狠。",
      tags: ["phd"],
      questions: [
        { ask: "你取得博士学位了吗？", bingo: "phd", yes: "拿到了。证比喜帖还薄。我是吴淼。" },
        { ask: "旁边那位也是博士？", bingo: null, yes: "对，小糖博士。我们一路互相改过摘要，今天改来喝喜酒。" },
        { ask: "博导来了吗？", bingo: null, yes: "没有，谢天谢地。" },
      ],
    },
    {
      id: "tangtang",
      name: "小糖博士",
      shirt: 0xe8b4c4,
      hair: 0x4a2818,
      hello: "叫我小糖就好。博士是真的，糖也是真的——包里还有两颗，怕典礼低血糖。吴淼让我别只顾着吃糖，先把 Bingo 聊完。",
      tags: ["phd"],
      questions: [
        { ask: "你取得博士学位了吗？", bingo: "phd", yes: "取得了。答辩那天我口袋里也揣着糖。我是小糖博士。" },
        { ask: "为什么叫小糖博士？", bingo: null, yes: "实验室熬夜全靠软糖续命，外号就留下来了。现在喜糖我也能专业点评。" },
        { ask: "你和吴淼怎么认识的？", bingo: null, yes: "组会相邻座位。他改语法，我改图表，今天终于改成宾客了。" },
        { ask: "喜糖好吃吗？", bingo: null, yes: "好吃。博士不研究这个，但实践很充分。" },
      ],
    },
    {
      id: "he",
      name: "何老师",
      shirt: 0xcfc6b8,
      hair: 0x5a4030,
      hello: "我是老师，改作业改到飞机上。",
      tags: ["teacher"],
      questions: [
        { ask: "你是老师吗？", bingo: "teacher", yes: "是。职业为老师，周末来当宾客。" },
        { ask: "学生知道你来喝喜酒吗？", bingo: null, yes: "知道。作业照常交。" },
      ],
    },
    {
      id: "xiaozhou",
      name: "小周",
      shirt: 0xe2b3c9,
      hair: 0x4a3028,
      hello: "巧了，我们家也是今年的婚期。",
      tags: ["wedyear"],
      questions: [
        { ask: "你也是今年结婚吗？", bingo: "wedyear", yes: "对，婚期也在今年。让我们一起祝福他们！" },
        { ask: "两边婚礼撞车吗？", bingo: null, yes: "差一点。还好差了一个月。" },
      ],
    },
    {
      id: "pai",
      name: "牌哥",
      shirt: 0x8a3030,
      hair: 0x1a1a1a,
      hello: "掼蛋赢过新郎。他到现在不承认。",
      tags: ["cards"],
      questions: [
        { ask: "你掼蛋或麻将赢过新郎新娘吗？", bingo: "cards", yes: "赢过。证据在聊天记录里。" },
        { ask: "待会赌坊去不去？", bingo: null, yes: "去。钟意那桌，大小我都敢押。" },
      ],
    },
    {
      id: "min",
      name: "小敏",
      shirt: 0xf0c27a,
      hair: 0x6a4030,
      hello: "带娃来的。我家臭臭两岁十个月，是个小男孩，今晚托人看着。",
      tags: ["chouchou"],
      questions: [
        { ask: "你是“臭臭”的爸爸或妈妈吗？", bingo: "chouchou", yes: "我是。两岁十个月的儿子，今晚托人看了。" },
        { ask: "臭臭是谁？", bingo: "chouchou", yes: "我们的儿子，两岁十个月的小男孩。我们就是臭臭的爸妈。" },
      ],
    },
    {
      id: "lv",
      name: "阿旅",
      shirt: 0x4f8f7b,
      hair: 0x2b2018,
      hello: "跟他们一起走过不少路，机票夹里全是旧登机牌。",
      tags: ["travel"],
      questions: [
        { ask: "你和新郎新娘一起旅过游吗？", bingo: "travel", yes: "旅过。丢过护照，也看过极光。" },
        { ask: "下次去哪？", bingo: null, yes: "蜜月他们自己定。我们负责鼓掌。" },
      ],
    },
  ],

  npcs: {
    attendant: {
      name: "接待姐姐",
      title: "签到台",
      avatar: "🌿",
      note: "【待补充：真实接待人员名字/口癖】",
    },
    zhong: {
      name: "小钟",
      title: "新郎",
      avatar: "🌙",
      note: "【待补充：个性化对白】",
    },
    xu: {
      name: "阿旭",
      title: "新娘",
      avatar: "🌻",
      note: "【待补充：个性化对白】",
    },
    host: {
      name: "主持人",
      title: "Party / 仪式",
      avatar: "🎙️",
      note: "【待补充】",
    },
    guest: {
      name: "邻座宾客",
      title: "新朋友",
      avatar: "🥂",
      note: "【待补充：可换成真实朋友】",
    },
    gardener: {
      name: "游园会向导",
      title: "Love Land",
      avatar: "🧺",
      note: "【待补充】",
    },
    awen: {
      name: "阿文",
      title: "破冰主持",
      avatar: "🎀",
      note: "和王老师一起发 Bingo、荧光棒和驱蚊液",
    },
    wang: {
      name: "王老师",
      title: "破冰主持",
      avatar: "📚",
      note: "和阿文一起介绍规则",
    },
    zhongyi: {
      name: "钟意",
      title: "赌坊",
      avatar: "🎲",
      note: "猜大小，收发筹码",
    },
    erjie: {
      name: "二姐",
      title: "开场舞领舞",
      avatar: "💃",
      note: "带着大家在台前跳",
    },
    cam: {
      name: "阿摄",
      title: "摄影",
      avatar: "📷",
      note: "宾客互动拍摄",
    },
    vid: {
      name: "阿录",
      title: "摄像",
      avatar: "🎥",
      note: "跟拍全程",
    },
    qianyi: {
      name: "芊一",
      title: "就餐引导",
      avatar: "🌙",
      note: "晚宴落座",
    },
    keman: {
      name: "珂满",
      title: "就餐引导",
      avatar: "🥂",
      note: "欢迎卡与 Party 流程",
    },
    prize: {
      name: "兑换姐姐",
      title: "游园会兑礼",
      avatar: "🎁",
      note: "游戏币换礼物",
    },
  },

  locations: {
    plane: {
      day: 0,
      name: "飞往成都的航班",
      blurb: "窗外是云海。你是一名小小宾客，正在赶赴一场婚礼。",
      art: "plane",
    },
    meadow: {
      day: 1,
      name: "右岸天鹅湖 · 草坪",
      blurb: "山林清幽。Party 与仪式都在这片草地上发生。",
      photo: "assets/venue.jpg",
    },
    checkin: {
      day: 1,
      name: "签到接待处",
      blurb: "16:00 起签到。领取 Bingo Card，再去拍一张合影。",
      icon: "📋",
    },
    ice: {
      day: 1,
      name: "破冰游戏区",
      blurb: "16:30–17:30 Before Party。认识新朋友，攒第一枚游戏币。",
      icon: "🎲",
    },
    buffet: {
      day: 1,
      name: "西餐自助 / BBQ",
      blurb: "17:30–19:00。先填饱肚子，再准备上场跳舞。",
      icon: "🍝",
    },
    party: {
      day: 1,
      name: "Before Party 主场",
      blurb: "19:00–21:30。暖场、开场舞、游戏、拍卖、大合唱。",
      icon: "💃",
    },
    afterparty: {
      day: 1,
      name: "月光 Afterparty",
      blurb: "灯串、月亮、香槟塔。中秋团圆的后半夜。",
      photo: "assets/afterparty.jpg",
      icon: "🌕",
    },
    gardenGate: {
      day: 2,
      name: "游园会入口",
      blurb: "09:20–11:20 签到、领券、领伴手礼，然后开始探索。",
      icon: "🚪",
    },
    photobooth: {
      day: 2,
      name: "Photo Booth",
      blurb: "藤蔓相框，留下一张 Love Land 合影。",
      icon: "📷",
    },
    games: {
      day: 2,
      name: "游戏区",
      blurb: "套圈圈 · 谁是雀神 · 户外羽毛球。参与即得币。",
      icon: "🎯",
    },
    diy: {
      day: 2,
      name: "DIY 区",
      blurb: "串珠、香囊、儿童手工桌。做一份带回去的小物件。",
      icon: "🧵",
    },
    dessert: {
      day: 2,
      name: "甜品区",
      blurb: "【待补充：甜品台细节】先甜一口，再去换礼。",
      icon: "🍰",
    },
    ceremony: {
      day: 2,
      name: "帆船仪式区",
      blurb: "11:28–12:00。向日葵与白帆之间，见证一句我愿意。",
      icon: "⛵",
    },
    banquet: {
      day: 2,
      name: "婚礼午宴",
      blurb: "12:00–14:00。共享美食与欢笑，谢谢你们的陪伴。",
      icon: "🥢",
    },
  },

  /**
   * 任务链：按 order 推进。unlock 依赖 flags。
   * type: travel | talk | action | minigame
   */
  quests: [
    {
      id: "q_plane",
      day: 0,
      order: 1,
      title: "飞向 Love Land",
      hint: "看向窗外，等一封信来。",
      location: "plane",
    },
    {
      id: "q_letter",
      day: 0,
      order: 2,
      title: "拆开纸船",
      hint: "点击纸船，读完邀请函。",
      location: "plane",
    },
    {
      id: "q_arrive",
      day: 1,
      order: 3,
      title: "抵达天鹅湖",
      hint: "请在 9.25 16:30 前到达指定地点。",
      location: "meadow",
      type: "travel",
    },
    {
      id: "q_checkin",
      day: 1,
      order: 4,
      title: "完成签到",
      hint: "去签到接待处，和接待姐姐说话。",
      location: "checkin",
      type: "talk",
      npc: "attendant",
    },
    {
      id: "q_ice",
      day: 1,
      order: 5,
      title: "破冰，认识一个人",
      hint: "到破冰区找邻座宾客聊两句。",
      location: "ice",
      type: "talk",
      npc: "guest",
    },
    {
      id: "q_buffet",
      day: 1,
      order: 6,
      title: "先吃饱再狂欢",
      hint: "去西餐自助，遇见新郎或新娘。",
      location: "buffet",
      type: "talk",
      npc: "zhong",
    },
    {
      id: "q_party",
      day: 1,
      order: 7,
      title: "参加 Before Party",
      hint: "到主场找主持人，走一遍游戏流程。",
      location: "party",
      type: "talk",
      npc: "host",
    },
    {
      id: "q_chorus",
      day: 1,
      order: 8,
      title: "合唱《干杯》",
      hint: "副歌会唱就可以。重要的是一起大声唱。",
      location: "party",
      type: "action",
    },
    {
      id: "q_moon",
      day: 1,
      order: 9,
      title: "走进月光里",
      hint: "Party 结束后，去 Afterparty 找阿旭。",
      location: "afterparty",
      type: "talk",
      npc: "xu",
    },
    {
      id: "q_gate",
      day: 2,
      order: 10,
      title: "领取入场券与伴手礼",
      hint: "第二天清晨，回到游园会入口签到。",
      location: "gardenGate",
      type: "talk",
      npc: "attendant",
    },
    {
      id: "q_explore",
      day: 2,
      order: 11,
      title: "收集 3 枚游戏币",
      hint: "Photo Booth / 游戏区 / DIY 区，任选三处打卡。",
      location: "games",
      type: "collect",
      needCoins: 3,
    },
    {
      id: "q_ceremony",
      day: 2,
      order: 12,
      title: "在树下见证誓言",
      hint: "11:28，请入座帆船仪式区。",
      location: "ceremony",
      type: "talk",
      npc: "host",
    },
    {
      id: "q_banquet",
      day: 2,
      order: 13,
      title: "午宴祝福",
      hint: "去午宴席，把心里的话交给他们。",
      location: "banquet",
      type: "talk",
      npc: "zhong",
    },
  ],

  partyFlow: [
    { t: "暖场视频", d: "10 min", todo: false },
    { t: "开场舞 · 你要跳舞吗", d: "5 min", todo: false },
    { t: "大屏游戏", d: "", todo: true },
    { t: "天选之子", d: "", todo: true },
    { t: "寻宝游戏", d: "", todo: true },
    { t: "两队 PK · 铁人五项", d: "俯卧撑 / 吸管喝酒 / 柠檬 / 缺牙齿 / 筛子", todo: false },
    { t: "两队 PK · 吹扑克", d: "赢筹码，输了喝豆汁", todo: false },
    { t: "猜歌名", d: "", todo: false },
    { t: "飞机大作战", d: "彩色卡纸", todo: false },
    { t: "听声音辨位", d: "输的惩罚穿衣服", todo: false },
    { t: "礼物拍卖", d: "8 个盲盒，币不够可用柠檬或喝酒兑换", todo: false },
    { t: "大合唱干杯", d: "", todo: false },
  ],

  partyActs: [
    { id: "screen", kind: "sim", title: "大屏游戏", text: "大屏随机点名。你被扫到一次，全场起哄。" },
    { id: "chosen", kind: "sim", title: "天选之子", text: "转盘停下。今晚天选之子不是你，松了一口气。" },
    { id: "hunt", kind: "sim", title: "寻宝游戏", text: "荧光棒当火把。你在花丛里摸到一张小纸条：Love Land。" },
    { id: "iron", kind: "sim", title: "铁人五项", text: "俯卧撑、吸管、柠檬、缺牙齿、筛子。你们组没有垫底。" },
    { id: "poker", kind: "sim", title: "吹扑克", text: "一口气吹飞。赢的那桌多了一叠筹码，输的喝豆汁。" },
    { id: "song", kind: "sim", title: "猜歌名", text: "前奏一响你就喊出来了。邻桌不服，再来一首。" },
    { id: "plane", kind: "sim", title: "飞机大作战", text: "彩色卡纸折成纸飞机，飞过长桌，有人接到，有人扣到汤里。" },
    { id: "sound", kind: "sim", title: "听声音辨位", text: "蒙眼听铃。你走偏了半步，惩罚是套一件奇怪外套。" },
    { id: "auction", kind: "sim", title: "礼物拍卖", text: "八个盲盒。你举了一次 50，被人加到 100。下次再抢。" },
    { id: "cheers", kind: "cheers", title: "大合唱干杯", text: "会不会有一天，时间真的能倒退……重要的是一起大声唱。" },
  ],

  gardenGames: [
    {
      id: "ring",
      name: "套圈圈",
      loc: "games",
      rule: "每人 3 个圈。参与得 1 币，套中再 +3 币。",
      coins: 1,
    },
    {
      id: "mahjong",
      name: "谁是雀神",
      loc: "games",
      rule: "30 秒内摸出 3 张指定麻将。参与 1 币，成功再 +3。",
      coins: 1,
    },
    {
      id: "badminton",
      name: "户外羽毛球",
      loc: "games",
      rule: "舒展身体，享受阳光与微风。参与 1 币，对打取胜再 +3。",
      coins: 1,
    },
    {
      id: "photo",
      name: "拍一张",
      loc: "photobooth",
      rule: "在藤蔓相框前留下合影。【待补充：pose / 道具】",
      coins: 1,
    },
    {
      id: "beads",
      name: "串珠 DIY",
      loc: "diy",
      rule: "挑选珠子和配饰，做一份独一无二的作品。",
      coins: 1,
    },
    {
      id: "sachet",
      name: "香囊 DIY",
      loc: "diy",
      rule: "自选香料，做一份属于自己的香囊。",
      coins: 1,
    },
    {
      id: "kids",
      name: "儿童手工桌",
      loc: "diy",
      rule: "石膏娃娃、绘画、创意手工。小朋友优先，大人也可以帮忙。",
      coins: 1,
    },
  ],

  dialogues: {
    awen_kit: [
      { who: "awen", text: "16:30 破冰开始！我是阿文，旁边是王老师。" },
      { who: "wang", text: "先领三样：Bingo Card、荧光棒、驱蚊液。晚上草地蚊虫认真的。" },
      { who: "awen", text: "规则很简单：去找宾客聊天，问对了格子，名字会自动写进 Bingo。" },
      { who: "wang", text: "写满整张卡，再回来找我们，换 50 面额筹码一枚。筹码今晚拍卖用。" },
      { who: "awen", text: "想快一点体验的话：打开右下角背包，点 Bingo Card，再点「一键全填并保存」。" },
      { who: "system", text: "获得 Bingo Card、荧光棒、驱蚊液。可以去交谈，也可以背包里一键全填。" },
    ],
    awen_wait: [
      { who: "wang", text: "还没写满哦。和宾客聊完会自动写入；想快体验就打开背包里的 Bingo Card，点「一键全填并保存」。" },
      { who: "awen", text: "大胆问。比如：请问你喜欢潜水吗？" },
    ],
    awen_reward: [
      { who: "awen", text: "写满了！这张卡比机票还满。" },
      { who: "wang", text: "按规则，换给你一枚 50 筹码。去找摄影拍一张，凳子下面好像还藏着筹码。草坪尽头是晚宴入口。" },
      { who: "system", text: "获得筹码 50。" },
    ],
    hotel_checkin: [
      { who: "attendant", text: "欢迎入住右岸天鹅湖。房间已经按婚礼宾客安排好了。" },
      { who: "player", text: "我刚从机场坐车过来。行李就这些。" },
      { who: "attendant", text: "入住办好了。16:30 草坪破冰，去找阿文和王老师领 Bingo。" },
      { who: "system", text: "新任务：找阿文和王老师领取 Bingo Card。" },
    ],
    ice_break: [
      { who: "guest", text: "你也赶到了！我们正缺一个人组队。" },
      { who: "player", text: "飞机加出租，一路跑来的。" },
      { who: "host", text: "破冰开始。先认识身边的人，Bingo Card 待会发。" },
      { who: "system", text: "你已经站在 Love Land 的草坪上了。后续 Party 关卡可以继续往下补。" },
    ],
    attendant_q_checkin: [
      { who: "attendant", text: "欢迎来到 Love Land。请问怎么称呼？" },
      { who: "player", text: "我是赶来参加婚礼的小小宾客。" },
      {
        who: "attendant",
        text: "签到完成。这是你的 Bingo Card，记得去拍一张合影。16:30 破冰游戏要开始啦。",
      },
      { who: "system", text: "获得 Bingo Card。下一站：破冰游戏区。" },
    ],
    guest_q_ice: [
      { who: "guest", text: "你也是坐飞机来的？我刚还在想，这场逃跑计划也太认真了。" },
      { who: "player", text: "纸船里的信我看了两遍。生命真是小概率事件。" },
      { who: "guest", text: "那我们碰一下杯。待会 Party 一起组队，铁人五项我可不想一个人做俯卧撑。" },
      { who: "system", text: "认识了一位新朋友。获得 1 枚游戏币。" },
    ],
    zhong_q_buffet: [
      { who: "zhong", text: "你终于到了。吃了吗？BBQ 和西餐都在，别空着肚子去跳舞。" },
      { who: "player", text: "新郎官今天看起来很镇静。" },
      { who: "zhong", text: "那是假象。待会《干杯》副歌我会唱，你也要来。重要的是一起大声唱。" },
      { who: "system", text: "肚子填饱了。主持人在 Party 主场等你。" },
    ],
    host_q_party: [
      { who: "host", text: "宾客入场！今晚流程很长：暖场、开场舞、大屏游戏、PK、拍卖，最后合唱。" },
      { who: "player", text: "我先把清单记在任务本上。" },
      { who: "host", text: "具体玩法他们还在打磨，你先走一遍场子。准备好了就去合唱区集合。" },
      { who: "system", text: "已领取 Party 流程清单。【玩法细节待补充】" },
    ],
    xu_q_moon: [
      { who: "xu", text: "灯串亮起来了。月亮是假的，心情是真的。" },
      { who: "player", text: "第一关过完了。明天还要早起去游园会。" },
      { who: "xu", text: "睡个好觉。明天 9:20 领 Love Land 入场券，11:28 我们在帆船前等你。" },
      { who: "system", text: "9.25 关卡完成。9.26 已解锁。" },
    ],
    attendant_q_gate: [
      { who: "attendant", text: "早上好。游园会 9:20 开始。先领入场券，再按姓名领专属伴手礼。" },
      { who: "player", text: "今天要收集游戏币，对吗？" },
      { who: "attendant", text: "对。套圈、雀神、羽毛球、串珠、香囊、拍照……完成挑战就能换礼。11:28 记得回仪式区。" },
      { who: "system", text: "获得 Love Land 入场券与伴手礼。" },
    ],
    host_q_ceremony: [
      { who: "host", text: "请入座。向日葵沿着过道开到白帆底下。" },
      { who: "player", text: "好安静。" },
      { who: "host", text: "他们要认真说出那句「我愿意」。请你做见证人。" },
      { who: "zhong", text: "……我愿意。" },
      { who: "xu", text: "……我愿意。" },
      { who: "system", text: "你见证了誓言。午宴开始了。" },
    ],
    dining_map: [
      { who: "system", text: "领取对应颜色手环，仪式结束后按桌号入席。对照座位图，找到自己那一桌坐下。" },
    ],
    dining_sit: [
      { who: "system", text: "入席了。白椅套已经拉开，玻璃转盘对着你。" },
      { who: "system", text: "菜还在上。在座位上再互动一次，就可以开吃。" },
    ],
    dining_eat: [
      { who: "system", text: "转盘转起来，菜一道一道上来。这顿吃得很饱。" },
      { who: "player", text: "该去和他们说再见了。" },
      { who: "system", text: "去 8 号「结婚」桌，和小钟阿旭告别再离开。" },
    ],
    zhong_q_banquet: [
      { who: "zhong", text: "谢谢你飞过来。也谢谢你把这两天一路闯过来。" },
      { who: "xu", text: "聚散有期，情谊无疆。吃饱，再把祝福留下。" },
      { who: "player", text: "祝有爱者更爱，独立者更自由。" },
      { who: "system", text: "闯关完成。Love Land 欢迎你随时回来补全更多支线。" },
    ],
    photo_take: [
      { who: "cam", text: "看镜头！荧光棒举起来——三、二、一。" },
      { who: "vid", text: "这段我跟拍了。晚上 Party 大屏也许能看到你。" },
      { who: "system", text: "获得一张现场合影。记得还有散落的筹码藏在凳子下面。" },
    ],
    hidden_chip: [
      { who: "system", text: "凳子下面压着一枚 100 筹码。有人过年时落下的吧。" },
    ],
    dinner_ready: [
      { who: "awen", text: "破冰收工。晚宴在草坪尽头，走「月光晚宴入口」就到。" },
      { who: "system", text: "前往就餐区。芊一和珂满在门口等你。" },
    ],
    qianyi_seat: [
      { who: "qianyi", text: "欢迎来到月光晚宴。长桌已经铺好，我是芊一，旁边是珂满。" },
      { who: "keman", text: "这是欢迎卡，还有今晚的 Party 流程。18:30 到 19:00 暖场，然后正式开始。" },
      { who: "qianyi", text: "先去白幕前找主持人。他会请你落座看暖场，再决定要不要跟二姐上台跳舞。" },
      { who: "system", text: "获得欢迎卡与 Party 流程单。" },
    ],
    host_start_party: [
      { who: "host", text: "麦克风好了。今晚先落座看暖场短片。" },
      { who: "host", text: "然后二姐会带开场舞——想上台就去台前找她。跳完回来，游戏一项一项过，最后合唱《干杯》。" },
      { who: "system", text: "去长桌空位坐下，观看暖场视频。" },
    ],
    erjie_dance: [
      { who: "erjie", text: "我先带着跳。台上已经有一排人了。你要不要上来？" },
    ],
    breakfast: [
      { who: "attendant", text: "早安。窗边那桌摆好了：可颂、果酱、水果、包子，还有一壶热茶。" },
      { who: "attendant", text: "昨晚没用完的筹码，已经按张数换成游戏币了。" },
      { who: "attendant", text: "9:20 游园会开门。先去找阿文和王老师签到，领门票、入场券和专属伴手礼。" },
      { who: "system", text: "去游园会签到处。" },
    ],
    day2_check: [
      { who: "awen", text: "早上好！先完成签到。这是你的门票，还有 Love Land 入场券。" },
      { who: "wang", text: "按姓名领取专属伴手礼——这份是给你的。接下来请按任务一项一项走。" },
      { who: "awen", text: "今天请按顺序走：先去 DIY 区，三项都能玩、任玩一项也能过关；再去 Photo Booth 合影；然后去游戏区三项都能玩、任玩一项过关；回这里兑奖；入座前再到我们这儿领问誓卡。11:28 开始婚礼。" },
      { who: "wang", text: "兑奖：一等奖 15 币，二等奖 10，三等奖 5，四等奖 3，参与奖 1。跟着任务提示走就不会走丢。" },
      { who: "system", text: "获得门票、入场券与伴手礼。先去 DIY 区。" },
    ],
    dessert_talk: [
      { who: "system", text: "甜品台铺着奶油色桌布，塔盘上摆着小蛋糕。你尝了一口，把心情也变甜了。" },
    ],
    ceremony_host: [
      { who: "host", text: "各位来宾请坐稳。11:28，Love Land 的仪式现在开始。" },
      { who: "host", text: "有请新郎小钟、新娘阿旭。他们已经站到白帆前。" },
      { who: "host", text: "请把掌声给他们。向日葵还在过道两边开着。" },
      { who: "host", text: "今天不由我一个人问。请举起问誓卡，全体亲友一起问他们：愿不愿意。" },
    ],
    collective_vow: [
      { who: "crowd", text: "小钟、阿旭——你们是否愿意，把余生过成一场认真的逃跑计划？" },
      { who: "crowd", text: "你们是否愿意，在树下彼此成为自由而靠近的人？" },
      { who: "zhong", text: "我愿意。" },
      { who: "xu", text: "我愿意。" },
      { who: "host", text: "请交换信物。把这一天认真说完。" },
      { who: "host", text: "我郑重宣布：他们结婚了。有请新郎新娘，把想对大家说的话，说完。" },
    ],
    vow_card: [
      { who: "awen", text: "兑奖完成。婚礼马上开始，先领这张问誓卡。" },
      { who: "wang", text: "入座后主持人一 cue，请大家一起举起卡片，齐声问他们愿不愿意。" },
      { who: "awen", text: "卡片上写着：你们是否愿意，把余生过成一场认真的逃跑计划？" },
      { who: "system", text: "获得问誓卡。去仪式区空座位坐下。" },
    ],
    couple_confession: [
      { who: "zhong", text: "谢谢你们飞过来。有人赶红眼航班，有人请假，有人带着孩子，有人把猫托给邻居。你们把这场逃跑计划变成真的。" },
      { who: "xu", text: "昨天的破冰、夜里的灯、今天的游园会，都有你们。Love Land 不是一个地方，是你们愿意来。" },
      { who: "zhong", text: "我曾以为自由是一个人走很远。后来发现，是有人愿意和我走同一条路，还不互相催。" },
      { who: "xu", text: "小钟，余生请多指教。也请在座的每一位，把今天的阳光和向日葵带走。" },
      { who: "zhong", text: "我们爱你们。请把掌声留给彼此，也留给自己——祝有爱者更爱，独立者更自由。" },
      { who: "xu", text: "婚礼到这里，认真说完了。去圆桌坐下来，把祝福交给我们。" },
      { who: "system", text: "告白结束。去室内圆桌午宴，对照座位图入席。" },
    ],
    prize_wait: [
      { who: "awen", text: "先按任务走：DIY、合影、游戏，然后再来兑奖。" },
    ],
    prize_talk: [
      { who: "awen", text: "兑奖在这里。选你够得着的那一档。兑完再来我们这儿领问誓卡。" },
    ],
  },
};
